### ISSUE TITLE
Question: Handover bot state in the connection hijack as well?

### ISSUE THREAD

**Issue by flexd** [whyrusleeping/hellabot#14]
I noticed the bot does some state tracking here https://github.com/whyrusleeping/hellabot/blob/master/ircchannel.go#L83

Perhaps it would be possible to hand over this state in the connection hijack as well?

**Comment by whyrusleeping** [comment]
Hrm... That would be nice to have.We could probably ensure that all gathered state is in a single 'state' object, and then serialize it over the connection after the file descriptor has been sent.

**Comment by flexd** [comment]
Closing this, since I've ripped that bit out of the bot anyway.. We would probably share any state via a database or something.
