### ISSUE TITLE
TODO: Figure out a way to do connection hijacking of SSL connections

### ISSUE THREAD

**Issue by flexd** [whyrusleeping/hellabot#21]
I am thinking maybe we could do something where there is a basic core of the bot that connects to the IRC server, and is it's own process, and then the bot would connect to that instead of the IRC server directly. That way you could restart the bot process as much as you'd like, and the IRC connection would stay up.

The core would have to deal with server PINGs on it's own, and just discard every other message when the bot itself is not connected. Not sure if this is too much work to be useful or if it just ends up being impractical. 

What do you think @whyrusleeping ?

**Comment by ugjka** [comment]
Maybe something like this https://github.com/jpillora/go-tcp-proxy/blob/master/proxy.go

**Comment by icholy** [comment]
@flexd are you still planning to work on this?

**Comment by flexd** [comment]
No, feel free to close it. It would be cool though, but it would basically need a irc connection proxy layer to keep the connection up and relay messages to/from connecting bot cores. I’m not going to be writing that 😬
