### ISSUE TITLE
Proposal: Add new Name field to Trigger struct to support comparing Triggers

### ISSUE THREAD

**Issue by bbriggs** [whyrusleeping/hellabot#30]
This all started when I wanted to do some live loading and unloading of triggers. I found that it was quite easy to load a trigger during runtime (in fact, I could load multiple instances of a trigger. Fun!)

However, the problem came with unloading. The most natural approach seemed to be to iterate over the `triggers` slice, compare all the triggers there with the one to remove, and then drop the match. However, none will match. Ever. By definition. 

Because the exported fields of the Trigger are functions, no two triggers can ever be equal, since no two functions can ever be equal to one another (can only be compared to `nil`). Well crap.

So, I thought to myself, either I can add something in my implementation that checks some sort of bool to see if the trigger is "on" (still doable) or I can add a new exported field that gives a trigger a unique name (and is therefore a comparable string). 

Regarding this last one, when I added the new field I realized that they way we have been defining Triggers means that it will break _all existing triggers unless they use the named fields or define a name_. Obviously this can present a large, breaking change. So rather than just toss a PR at this repo, I decided to open an issue so we can discuss it here. In the meantime, you can take a look at [my fork](https://github.com/bbriggs/hellabot/tree/drop-trigger) and an implementation of the [new hot loading/unloading setup](https://github.com/bbriggs/bitbot) to see it in action.

Looking forward to your thoughts here.

**Comment by icholy** [comment]
I'm not against extending the api to support your use case, but lets spend some more time thinking about a backwards compatible way to add it.

**Comment by bbriggs** [comment]
Agreed. This is just my exploration of how to do it.
