### ISSUE TITLE
Proposal: Stateful Store in Bot struct

### ISSUE THREAD

**Issue by bbriggs** [whyrusleeping/hellabot#35]
I've been using (wrapping, really) Hellabot for a while in [bitbot](https://github.com/bbriggs/bitbot) and hacking around the lack of a stateful store by making `bot` a global (gross). I'd like to let triggers have access to a stateful store and methods via `hbot.Bot` so that they don't have to go outside their scope for this sort of thing.

[bbolt](https://github.com/etcd-io/bbolt) is a pure-go key/value store that has been working well for my use case and one I'd recommend if this proposal moves forward.

I know adding fields to the struct can be a painful thing so I'm open to alternatives here. In the meantime, I'm going to fork and play around with this idea on my own branch like I did last time with NamedTriggers.

**Comment by icholy** [comment]
I think a storage solution is out of scope for this project.
