### ISSUE TITLE
Need hijackSession handler for BSD

### ISSUE THREAD

**Issue by bbriggs** [whyrusleeping/hellabot#40]
When installing packages that link hellabot on BSD, there is no hijackSession handler for that kernel. 

```
# github.com/whyrusleeping/hellabot
../go/src/github.com/whyrusleeping/hellabot/hellabot.go:226:15: bot.hijackSession undefined (type *Bot has no field or method hijackSession, but does have HijackSession)
../go/src/github.com/whyrusleeping/hellabot/hellabot.go:242:8: bot.StartUnixListener undefined (type *Bot has no field or method StartUnixListener)
```

Kernel info:
`FreeBSD freebsd.daemon.space 12.1-RELEASE-p3 FreeBSD 12.1-RELEASE-p3 r359210 GENERIC  amd64`

**Comment by icholy** [comment]
@bbriggs can you test if the current linux implementation works on BSD?

**Comment by icholy** [comment]
I updated it to use the empty default implementation for now. https://github.com/whyrusleeping/hellabot/commit/1ea75c7dc208e69c69d330273d6ba35fff38161d

**Comment by bbriggs** [comment]
I'll try to get a BSD VM up to test on.

**Comment by ugjka** [comment]
Try https://github.com/whyrusleeping/hellabot/pull/44
